[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "NFT"

[constants]
TOTAL_NFTS = { type = "u64", value = "2" }

[dependencies]
# storage_string = { git = "https://github.com/FuelLabs/sway-libs" }
# string = { git = "https://github.com/FuelLabs/sway-libs" }
