/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.46.0
  Forc version: 0.40.1
  Fuel-Core version: 0.19.0
*/

export type { Src20Abi } from './Src20Abi';

export { Src20Abi__factory } from './factories/Src20Abi__factory';
